### ISSUE TITLE
High level molecular food component hierarchy

### ISSUE THREAD

**Issue by ddooley** [FoodOntology/joint-food-ontology-wg#13]
We have had a need in OBOFoundry for a **molecular food component hierarchy** (tentative name), having a root "food bioactive molecule" (again, tentative name) class.  We should work on the upper level of this as a separate table from the Diet Definitions table we've been finalizing.  **EDIT: I have put this in as a Nutrient Definitions tab of the [Dietary Table](https://docs.google.com/spreadsheets/d/18Ml5pLHfd0IVGD3roxF0NkjXRry0rRrsa8Y06y2fgr0) sheet.** 
 Then we can start loading that table up with terms, hierarchy and definitions as per above and other discussions.  (Some general terms are in there at top for reference in axioms for robot creation of an owl file). 

This is a big next step! I've been looking forward to it for over a year.

I'll need to assign google-specific accounts for editing rights on it, so for those who want, send me yours. I had to tighten up security on the diet term table recently. If your ontology already has an ID for one of the terms listed, put it in a row, otherwise lets just auto-increment TERM_XXXX in same fashion as Diet Definitions tab.

Now I realize this is a similar situation to the diet terms in that we are fashioning a more focused hierarchy, with multiple stakeholders from different ontologies involved.  Graham King & co. have referenced me to a [nutrition hierarchy scheme](https://www.researchgate.net/publication/337451986_Bridging_the_Food_Security_Gap_an_information-led_approach_to_connect_dietary_nutrition_food_composition_and_crop_production) that they aim to use in CDNO (vision paper [here](https://acsess.onlinelibrary.wiley.com/doi/full/10.1002/csc2.20092)).  For community buy-in we should all look at the schema, and sort out any BFO/OBOFoundry or process ontology or professionally-related preferences.

From the CDNO vision paper: "The population of terms within the [CDNO: dietary nutritional components] will make use of data definitions structured within a branched hierarchical nutrition schema recently developed by Azman Halimi et al. (2019), which presents a systematic and relevant well‐defined classification, drawing on the classification already described by Latham (1997) and the USDA Food Composition databases (https://ndb.nal.usda.gov/ndb/).

The parallel question is which ontology/ies have the curation context to shoulder all or part of this hierarchy, and it sounds like CDNO may have some capacity there, but I suggest we address that after stakeholder understanding/requesting of scope here.

**Comment by LCCarmody** [comment]
Ah! Thanks for adding this ticket!  I keep meaning to add items under this, as we would like many terms.  I will definitely contribute.  We were thinking this would be part of FoodOn, but I do understand if that is out of scope.  The reason we would like it in FoodOn however are for examples like this: Ex., Avoid trimethylamine and Choline for patients with [primary trimethylaminuria](https://www.ncbi.nlm.nih.gov/books/NBK1103/#trimethylaminuria.Management).  Foods to avoid include eggs, liver, kidney, peas, beans, peanuts, soya products, and brassicas (Brussels sprouts, broccoli, cabbage, cauliflower) as well as rapeseed products such as oil and flour. 

Our recommendations are to avoid a food component, but often the nutritional and medical recommendation highlights foods that are high in this component. 

For most of the metabolic disease, the recommendation is to avoid, but there are some that suggest supplementation of a food component and list a set foods.

**Comment by ddooley** [comment]
Regardless of which ontology ultimately hosts the food bioactive molecule hierarchy, FoodOn will include it, and can hold those axioms you have examples of!

**Comment by ddooley** [comment]
And just to say, FoodOn welcomes this hierarchy directly, but if there is a more domain specific ontology that has the curation wherewithal to take these on, we appreciate the strength of that.  The main thing for us is to synchronize on term definitions and usage, to eliminate redundancy within OBOFoundry.

**Comment by ddooley** [comment]
Just a note that CDNO will be introducing a nutritional hierarchy (based on USDA SR nutrient and INFOODS and CHEBI) that FoodOn will reuse, and will contribute to.  Looks like that is likely in the next few months.

**Comment by ddooley** [comment]
FoodOn now imports CDNO, so this is essentially resolved.
