### ISSUE TITLE
Evolve the Ontology for Nutrition Epidemiology (ONE) into a “pure” ontology model of dietary surveys

### ISSUE THREAD

**Issue by cyang0128** [FoodOntology/joint-food-ontology-wg#16]
After having a fantastic discussion with @ddooley and getting nice comments during the Food Ontology Workshop (IFOW), we are happy to announce that part of ONE has been evolved into a pure ontology model of dietary surveys. 

The classes about dietary assessment method (food surveys) are arranged under the OBI class "Investigation" (OBI:0000066), because doing a survey includes planning, design execution and documentation process. Moreover, the classes about quality description of surveys are arranged under the BFO class "Quality" (BFO:0000019).

Definitions of all the surveys are available, which are collected from authoritative documents (e.g. FAO reports) or published dictionaries (e.g. from Oxford University Press). 

As an instance, the class "FFQ/Food Frequency Questionnaire" is presented below.

We are eager to have your comments about the ontology structure before releasing the next version of ONE. 👍 Thank you!

![figure](https://user-images.githubusercontent.com/29631852/94993976-ee862700-0594-11eb-96de-46a88c39abbd.png)

![one term](https://user-images.githubusercontent.com/29631852/94994414-bf24e980-0597-11eb-9b18-b04f45bad6e3.png)

**Comment by ddooley** [comment]
I'm really appreciating the transformation of ONE, especially positioning under BFO.  @cyang0128 shall we schedule a call to go over the new organization?  I think there's still some finessing to do re. process term labels for example.

**Comment by ddooley** [comment]
One other note, in BFO parlance qualities are primarily about material entities - and perhaps qualities of processes (that has been debated over the years).  Information Content Entities (ICE) are bits of information about other material or immaterial things.  So we'll want to figure out if your quality descriptors might be ICE classes.

**Comment by cyang0128** [comment]
@ddooley thanks a lot! yes, it would be more appropriate to put the quality descriptors under ICE classes. I will check the ICE classes and update ONE accordingly. Shall we do the call next week?

**Comment by ddooley** [comment]
ONE now has these changes, so closing this issue.
