### ISSUE TITLE
Defining a food material vs a food product

### ISSUE THREAD

**Issue by oldskeptic** [FoodOntology/joint-food-ontology-wg#18]
Trying to align schema.org, gs1 and the beer ontology. **FOODON_00001260**
 (beer beverage) subclasses **FOODON_00001002** (food product altname food product type) which subclasses **FOODON_00002403** (food material).

**FOODON_00001002** food product is defined as "...Here classes are provided to differentiate a food product by its food composition, processing and/or consumption characteristics. This avoids brand name products but it may include generic food dish categories..."  so this isn't what schema.org and gs1 have in mind for "product" which is fine.

Meanwhile **FOODON_00002403** is defined as "Any substance that can be consumed by an organism to satisfy nutritional or other health needs, or to provide a social or organoleptic food experience". 

It's tempting to read this a "primary ingredients" vs "processed food / dish / meal as actually eaten", but **FOODON_00002451**  (food transformation process) has **FOODON_00002403** as it's defined output which includes both cooking, harvesting and processing which confuses the issue since that gives you everything you need to model properly without **FOODON_00001002**. ...so if it isn't a commercial product, or a eatable end-product, what it a foodon food product?

Generically I'm trying to align "Branded Beer Product", "Beer product (w/ style)" and Beer (generic) in Myra-Analytics/beer#2 to avoid redundancy. Ideally, we can define a generic "Stout Beer" brewed using these generic ingredients with this generic process.

**Comment by maweber-bia** [comment]
hi "oldskeptic" ! Best wishes !
This example about beer products is a very good way to tackel the issue: I mean the different in/out products through the food chain
It seems to me that we have to distinguish between raw primary products (= outputs of the harveting process), then primary derived product + secondary derived products (= outputs of the food transformation process, one or two "stages", that is "primary derivatives + composite/more complex food products) and so  finally we have the "generic food products" as outputs of the generic processes

I  agree with the distinction you have pointed out for beer, namely "Branded Beer Product", "Beer product (w/ style)" and Beer (generic), with commercial branded products referring  to one generic food product or food product (w/ style) 

Finally the question is what is a eatable end-product (or drinkable end-product) ?

**Comment by ddooley** [comment]
Thanks for raising the food product semantic discussion!

So far I've tried to distinguish between "food material" and "food product" with recognition that food material at a biological level isn't necessarily productized (via human processes).   Food Product is now defined as "**Food material for humans and animals which is processed with the intention that it be consumable as a whole or added to other food products.**"   (Your defn. above is from rdfs:comment annotation, and may have reflected a previous defn.) I have advocated that "food product" comes into being basically when industrial, agriculture or wild harvesting processes intentionally modify/rear a food material.

Food material sits above food product to accommodate a few things (diagram at bottom of foodon.org illustrates):
- chemical constituents in food that are measured but that themselves are not commodified, e.g. biomarkers, some kinds of nutrients, and bioactive compounds just being discovered/understood. E.g. selenium content in pasta.
- Food material such as corn or wheat chaff that gets diverted to other uses: corn diverted to biofuel, and e.g. https://www.designnews.com/materials-assembly/corn-wheat-rice-trash-make-concrete-stronger

So distinction between food material and subclass food product is highlighted by the difference in ingredient list vs nutritional labelling. All ingredients are food products, but quite a number of nutrients aren't themselves food products per se.

And yes, the closer one gets to output of harvesting process, the closer one gets to a general concept of "raw" or "**primary ingredient**".  But I would say our focus now on the [FoodOn Organismal Materials](https://docs.google.com/spreadsheets/d/1VJtz4m67tdUNDqRe3m1Okdxll64nTR46GSvCOmb0APE/edit#gid=0) table which contains organism x anatomical part will become the fundamental home for primary ingredients. We're working on moving all such simple foods (and their minimally informative reference, i.e. table may mention wheat grain but not whether it is dried or not) into this table [which then is used as an import file for FoodOn]. We will have a second table covering precomposed terms for very basic processing of such organism x anatomical part, such as whether a given grain, seed, etc. has been dried.

**Comment by oldskeptic** [comment]
Ok, so I would soften the definition of the food product with respect to processing so that we can get away with Apple **FOODON_00002473** being both a food product and a food material which accounts for both Apple-as-a-food and Apple-as-an-ingredient-to-an-apple-pie. We'll use FOODON_00001002 for upper food Products.
