### ISSUE TITLE
Requesting Hops Class

### ISSUE THREAD

**Issue by JessSing** [FoodOntology/joint-food-ontology-wg#19]
Please add a Hops class to FOODON

Feel free to use my definition, please reference with owl:equivalentClass  rdf:resource="https://rdf.ag/o/hops#Hops".

> H. lupulus has the most value of this genus as the flowers or 'hops' are a key ingredient in beer. This species is mostly grown in the Northern Hemisphere (between 35˚ and 55˚N) but it is also cultivated in Australia, New Zealand and South Africa.

**Comment by ddooley** [comment]
I think this is http://purl.obolibrary.org/obo/NCBITaxon_3486 Humulus lupulus right?
I see it has 4 subspecies that look useful so we'll bring those in too.
Adding definitions on top of NCBITaxon species that don't have them is a little tough but will try. Issue is the OBOFoundry principle of defining something in an Aristotelian fashion would pale in comparison to all the taxonomic differentiae at work.

**Comment by ddooley** [comment]
P.s. foodon has a "hops plant" http://purl.obolibrary.org/obo/FOODON_03411517  but we will deprecate that in favour of the NCBITaxon term.

**Comment by JessSing** [comment]
Ok, I will add an equivalency to http://purl.obolibrary.org/obo/NCBITaxon_3486  in The Hops Ontology.

**Comment by ddooley** [comment]
I think this can be closed now.  FoodOn has also deprecated "hops plant" in favour of the NCBI term; and its varietals will be imported shortly.
