### ISSUE TITLE
A list of terms about food-based dietary guidelines: checking overlap

### ISSUE THREAD

**Issue by cyang0128** [FoodOntology/joint-food-ontology-wg#21]
Dear ontology curators, we have introduced a list of terms in the Ontology for Nutritional Epidemiology (ONE) to annotate food-based dietary guidelines (please find the list of terms here: https://github.com/cyang0128/Nutritional-epidemiologic-ontologies/issues/2). The list of terms will be used for the European project "An integrated approach to the challenge of sustainable food systems: adaptive and mitigatory strategies to address climate change and malnutrition (SYSTEMIC)".

I have checked Ontobee, and have not found existing terms in this aspect. NCIT holds a term, which only indicate the reference values rather than the general guidelines (http://purl.obolibrary.org/obo/NCIT_C93234).

I post it as an issue here, in order to further avoid/check potential overlap. Please let me know if you have such existing terms in your ontology. Any other comments are also very welcome. Thanks a lot!

![image](https://user-images.githubusercontent.com/29631852/107602235-3135cb00-6c29-11eb-89e1-b701d770ba71.png)

**Comment by ddooley** [comment]
Looks good to me!

**Comment by ddooley** [comment]
Can we close this now?

**Comment by cyang0128** [comment]
@ddooley Yes, thanks!!!
