### ISSUE TITLE
Fasting as a general process vs fasting protocol

### ISSUE THREAD

**Issue by ddooley** [FoodOntology/joint-food-ontology-wg#7]
This issue is for feedback on two terms, one defining fasting as a process, and the other as a protocol that a fasting process would adhere to. 

label: fasting process
parent: process
definition: A food consumption process in which the timing of food and liquid ingestion is limited.
synonyms: fasting

label: fasting protocol
parent: protocol 
definition: A protocol that specifies the timing of food consumption.
synonyms: fasting schedule
example of use: The fasting protocol indicated fasting for 16 hrs per 24 hrs for a duration of 3 months.

We could have a food management process that has a fasting process as part (with its fasting protocol), and which may have a food selection protocol.

**Comment by ddooley** [comment]
For a parent, "food integration process" or "food management process" would be better than "food consumption process".  See https://github.com/FoodOntology/joint-food-ontology-wg/issues/8

**Comment by ddooley** [comment]
The fasting protocol would be a schedule of times of allowed food intake.   Parent of the fasting process would be "organism food management process".

**Comment by FrancescoVit** [comment]
We could close, this is in the latest ons.owl see 
https://github.com/enpadasi/Ontology-for-Nutritional-Studies/issues/6 
https://github.com/enpadasi/Ontology-for-Nutritional-Studies/issues/1
#10
