### ISSUE TITLE
prescribed diet / medically prescribed diet / dietetic diet

### ISSUE THREAD

**Issue by ddooley** [FoodOntology/joint-food-ontology-wg#9]
We currently have
id: ONS:0000082 
label: **prescribed diet**
definition: "A diet prescribed by a physician or nutritionist to meet **specific nutritional needs** of a person. "

I'm proposing this be renamed to: "**medically prescribed diet**", with synonym "dietetic diet".  However, the ONS definition mentions "specific nutritional needs". This is true in a number of cases, but in other cases its not so much about nutrition but other impacts on health, e.g. coeliac diet is about "A diet designed to reduce the symptoms of Coeliac disease which is caused by a reaction to gliadin (a gluten protein found in wheat) and similar proteins found in other crops."
.  So can the ONS definition have "**specific nutritional needs**" part replaced with "**health objectives**"?

Then we can have a "prescribed diet" parent which has both medically prescribed diet and self-prescribed diet", to distinguish between diets people have cooked up for themselves.

**Comment by ddooley** [comment]
And one other question - my tendency is to generalize dietary vocabulary where possible to apply to animals as well as people, so using "organism" or maybe "individual" rather than "person".  But I know this sounds awkward to nutritionalists working solely in the human world.  Our lab and a few others do have One-Health mandates, which - especially with crossover between mammalian research - suggest a general layer of terms applying to all organisms. If we don't provide diet terms that apply to animals, then we end up with a second mirror vocabulary for veterinarians and researchers which is dare I say even more awkward and a barrier to data analysis. People's thoughts?

**Comment by ddooley** [comment]
To drive home the point about animal research vs human & terminology: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3480308/ "Important Lessons Derived From Animal Models of Celiac Disease"

**Comment by maweber-bia** [comment]
> 
> 
> And one other question - my tendency is to generalize dietary vocabulary where possible to apply to animals as well as people, so using "organism" or maybe "individual" rather than "person". But I know this sounds awkward to nutritionalists working solely in the human world. Our lab and a few others do have One-Health mandates, which - especially with crossover between mammalian research - suggest a general layer of terms applying to all organisms. If we don't provide diet terms that apply to animals, then we end up with a second mirror vocabulary for veterinarians and researchers which is dare I say even more awkward and a barrier to data analysis. People's thoughts?

Here at INRAE we also use the concept of "One Health". I think "organism" is the broadest term we can use, but it is also right that nutritionist or food scientist would prefer "human" or "person" when dealing with food (and not feed).

Perhaps, we could specialized "organism" into sub-concepts for the terms which specifically apply to human-being (ie, food and diet) ? Is there a way to do so ?

**Comment by maweber-bia** [comment]
> 
> 
> To drive home the point about animal research vs human & terminology: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3480308/ "Important Lessons Derived From Animal Models of Celiac Disease"

Very good example. It reminds that we should consider animals as "experimental models" to study physiological function or pathologies before performing clinical studies.
Is there  a place to consider these models in the ontology ? It would be of particular interest for allergy (my lab is dealing with this topic research, and I was thinking of a use case about the impact of food transformation on allergenicity ... but this is another issue)

**Comment by ddooley** [comment]
"Perhaps, we could specialized "organism" into sub-concepts for the terms which specifically apply to human-being (ie, food and diet) ? Is there a way to do so ?"

This is what ontologies are good at!  Indeed, a general case of a diet term for all mammals at least, if not organism in general, could have subclasses targeted at humans.  It would be great to have more buy-in on this.

**Comment by FrancescoVit** [comment]
> . So can the ONS definition have "**specific nutritional needs**" part replaced with "**health objectives**"?

> Here at INRAE we also use the concept of "One Health". I think "organism" is the broadest term we can use, but it is also right that nutritionist or food scientist would prefer "human" or "person" when dealing with food (and not feed).

Would say yes!

It should also be inside the scope of ONS to describe both studies with human participants and studies with animals participants as model. (and this maybe rise a point if in the specific case of animal model in a human-oriented study, we should name it as "food" or "feed"). Hence it is true that in those cases we would have a problem with the "person" reference in definition, and would need two separate terms for human subjects and animal subjects. I do not think this is useful in the very end, so you find me in agreement on changing "person" to **"organism"** as the broader term. I am right now involved in a nutritional study on red meatconsumption and risk of CRC, and we have both human volunteers and animal model. So it is not totally true that only veterinarians need more general terms. 

On the other hand, I find less attractive to divide the "organism" concept. I think that the concept should be general, and we can further define the organisms with annotations referring to the NCBItaxonomy. So, referring to mixed studies, as the one I was introducing before, the same semantics would be good for describing the nutritional intervention on human and on rats, with the exception that the **prescribed diet** (or intervention diet as it is now in ONS) istance would be connected to different taxonomy. Does it sound right?

**Comment by LCCarmody** [comment]
I'm good with the points outlined, including

- ""specific nutritional needs" part replaced with "health objectives""

- prescribed diet being a parent of 'medically prescribed diet'

- species non-specific diet terms

My 2 cents is that maybe 'medically prescribed diet' could be 'clinically prescribed diet' or at least be a synonym.  There does seem to be controversy about which to use and often they are used interchangeably, but I think clinical is more broad and largely used more for treatment and diagnostics. Either way, they both should be synonyms.

And secondly, I support species non-specific terms and using 'individual' or 'population' to indicate the diet user.  We have not, but have discussed making MAxO human specific by designating 'human patient' in the logical axioms, but we decided against it for several reasons

**Comment by ddooley** [comment]
Clinical I think of as medical practitioner, physician etc, but if One Health people are ok with that, and it covers veterinarian, I am too.  So the revision then recommended:  

id: ONS:0000082
label: clinically prescribed diet
synonym: medically prescribed diet; dietetic diet
parent: prescribed diet
definition: "A diet prescribed by a dietitian, physician or nutritionist to meet health objectives of an organism."

**Comment by ddooley** [comment]
It looks like "dietetic diet" is a synonym for "clinically prescribed diet" since the diets in question may be motivated by nutritional concern or by allergy etc.

dietetic
adjective: pertaining to diet or to regulation of the use of food.; prepared or suitable for special diets, especially those requiring a restricted sugar intake.
noun: dietetics, (used with a singular verb) the science concerned with the nutritional planning and preparation of foods.

**Comment by laurenechan** [comment]
I like the direction of this term and agree clinical > medical for this purpose. One quick note, dietitian is technically spelled without a "c", at least in the US (although it's notably spelled incorrectly in many publications). Great new term!

**Comment by ddooley** [comment]
I believe we can close this thread now?!
